### ISSUE TITLE
after logstash disconnect reconnection is not made

### ISSUE THREAD

**Issue by hellysmile** [wikibusiness/aiologstash#17]
```
Nov 25 15:23:21 ip-172-31-43-190 run_server: 2017-11-25 15:23:21 +0000 WARNI [aiologstash] Unexpected exception while sending log
Nov 25 15:23:21 ip-172-31-43-190 run_server: Traceback (most recent call last):
Nov 25 15:23:21 ip-172-31-43-190 run_server: File "/opt/python3/lib/python3.6/site-packages/aiologstash/base_handler.py", line 76, in _work
Nov 25 15:23:21 ip-172-31-43-190 run_server: await self._send(data)
Nov 25 15:23:21 ip-172-31-43-190 run_server: File "/opt/python3/lib/python3.6/site-packages/aiologstash/tcp_handler.py", line 32, in _send
Nov 25 15:23:21 ip-172-31-43-190 run_server: self._writer.write(data)
Nov 25 15:23:21 ip-172-31-43-190 run_server: File "/opt/python3/lib/python3.6/asyncio/streams.py", line 294, in write
Nov 25 15:23:21 ip-172-31-43-190 run_server: self._transport.write(data)
Nov 25 15:23:21 ip-172-31-43-190 run_server: File "uvloop/handles/stream.pyx", line 632, in uvloop.loop.UVStream.write (uvloop/loop.c:74658)
Nov 25 15:23:21 ip-172-31-43-190 run_server: File "uvloop/handles/handle.pyx", line 150, in uvloop.loop.UVHandle._ensure_alive (uvloop/loop.c:54963)
Nov 25 15:23:21 ip-172-31-43-190 run_server: RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x2085318>; the handler is closed
```

**Comment by hellysmile** [comment]
https://github.com/wikibusiness/aiologstash/blob/master/aiologstash/base_handler.py#L77

should be `RuntimeError` as well

**Comment by hellysmile** [comment]
maybe here as well https://github.com/wikibusiness/aiologstash/blob/master/aiologstash/base_handler.py#L94
